### ISSUE TITLE
LICENSE file is not included in pypi source distribution file

### ISSUE THREAD

**Issue by nicola-lunghi** [altdesktop/python-dbus-next#15]
in the file for the sources

https://files.pythonhosted.org/packages/77/b2/60df113315e95e500b13029bed667cf5c23ea8ca2d586ccfa2d85a30be7a/dbus_next-0.1.2.tar.gz

the LICENSE file is not included

**Comment by acrisci** [comment]
Oh ok, the intention is to include the license file in the repo.

**Comment by nicola-lunghi** [comment]
Hi I'm asking because I just did a yocto recipe for dbus-next
http://lists.openembedded.org/pipermail/openembedded-devel/2019-October/202347.html

and yocto is downloading the source and it has a check to see if the license has changed.

For now I'm checking the sha of the PKG-INFO file but would be better to have a separate LICENSE file

thanks for your library :-)
