### ISSUE TITLE
The name org.freedesktop.NetworkManager was not provided by any .service

### ISSUE THREAD

**Issue by smnodame** [altdesktop/python-dbus-next#152]
I got this error message `dbus_next.errors.DBusError: The name org.freedesktop.NetworkManager was not provided by any .service files`

this is my code
```
from dbus_next.aio import MessageBus
import dbus_next.aio as dbus
import asyncio


async def main():
    bus = await MessageBus().connect()
    introspection = await bus.introspect('org.freedesktop.NetworkManager', '/org/freedesktop/NetworkManager')
    bus.get_proxy_object('org.freedesktop.NetworkManager', '/org/freedesktop/NetworkManager')
```

I have this bus path in my laptop
![Screenshot from 2023-03-30 16-41-20](https://user-images.githubusercontent.com/2629590/228796292-90c9c2be-0c38-44d7-94ba-c506d859e261.png)

and I have a question, why do I need this introspection, I used dbus-next in javascript before and it doesn't require
https://www.npmjs.com/package/dbus-next

**Comment by michallowasrzechonek-silvair** [comment]
You're connecting to the session bus. See `bus_type` argument.

**Comment by smnodame** [comment]
OK got it. thank you so mucn
