### ISSUE TITLE
Write a class like dbus object handler

### ISSUE THREAD

**Issue by nicola-lunghi** [altdesktop/python-dbus-next#17]
Hi,
sorry this is probably me not being familiar a lot with python3 and asyncio but....

I need to replace pyconnman (a library to manage connman, a connection manager, with python via dbus) because I'm using asyncio as my main loop

I was looking at dbus-next and in the regular dbus library I can describe a dbus proxy object with a class like this

https://github.com/liamw9534/pyconnman/blob/3f904c2c86996ac7b4ece572cb7113e572d40b40/pyconnman/agent.py#L32-L35

```
class GenericAgent(dbus.service.Object):

    @dbus.service.method("net.connman.Agent",
                                          in_signature='', out_signature='')
    def Release(self):
        pass
```

How can I translate this with dbus-next?

Thanks
Nicola Lunghi

**Comment by acrisci** [comment]
An overview is [here](https://python-dbus-next.readthedocs.io/en/latest/high-level-service/index.html) with examples.

**Comment by michallowasrzechonek-silvair** [comment]
The example is about services, and I think the OP asks about the client side... For this, you don't need to declare the proxy at all - use introspection instead:

```python3
introspection = await bus.introspect('net.connman', '/net/connman/agent')
proxy_object = bus.get_proxy_object('net.connman', '/net/connman/agent', introspection)
proxy_interface = proxy_object.get_interface('net.connman.Agent')

await proxy_interface.call_release()
```

It's all neatly documented in https://python-dbus-next.readthedocs.io/en/latest/high-level-client/index.html

**Comment by nicola-lunghi** [comment]
Hi thanks!
only one thing @michallowasrzechonek-silvair 
the 
```proxy_interface.call_release()```
is to "destroy" the proxy object or is just an example?
Thanks

**Comment by michallowasrzechonek-silvair** [comment]
No, it's just how dbus-next wraps remote methods. E.g. dbus `Release` is exposed on the python side as `call_release`.

**Comment by acrisci** [comment]
That's right, it builds the class based on the xml introspection data. To get a feel for it, try `print(dir(proxy_interface))`.
