### ISSUE TITLE
bluez - org.bluez not provided by any service

### ISSUE THREAD

**Issue by redmuchroom** [altdesktop/python-dbus-next#18]
Hi,

I'm currently trying to setup a dbus communication with bluez.
I'm able to get informations from bluez with their provided scripts (test-devices for example). I just want to point out that there is communication with bluez...

when I try do get information with dbus-next, it is not working, it reply that:

> the name "org.bluez" was not provided by any .service files

in the folder with the service files i get: 
> dbus-org.bluez.service

in the file i've : 

> [Unit]
Description=Bluetooth service
Documentation=man:bluetoothd(8)
ConditionPathIsDirectory=/sys/class/bluetooth

> [Service]
Type=dbus
BusName=org.bluez
ExecStart=/usr/libexec/bluetooth/bluetoothd --experimental
NotifyAccess=main
#WatchdogSec=10
#Restart=on-failure
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
LimitNPROC=1
ProtectHome=true
ProtectSystem=full

> [Install]
WantedBy=bluetooth.target

I've been able to introspect with "org.bluez.obex" but I would like to use the "org.bluez". (note that with "org.bluez.obex" I've not been able to use the methods...i get the message that the method doesn't exist).

also if I do : 
  `dbus-send --system            \
  --dest=org.freedesktop.DBus \
  --type=method_call          \
  --print-reply               \
  /org/freedesktop/DBus       \
  org.freedesktop.DBus.ListNames `

I get: 
>
      string "org.freedesktop.DBus"
      string ":1.7"
      string "org.freedesktop.login1"
      string ":1.72"
      string ":1.9"
      string ":1.73"
      string ":1.51"
      string "org.freedesktop.DisplayManager"
      string ":1.52"
      string "org.freedesktop.systemd1"
      string "org.freedesktop.PolicyKit1"
      string "org.freedesktop.Avahi"
      string "org.bluez"
      string ":1.32"
      string ":1.89"
      string "org.freedesktop.PackageKit"
      string "org.freedesktop.UDisks2"
      string ":1.13"
      string ":1.0"
      string ":1.14"
      string ":1.1"
      string ":1.15"
      string ":1.2"
      string ":1.16"
      string ":1.3"
      string ":1.17"
      string "fi.epitest.hostap.WPASupplicant"
      string ":1.4"
      string "fi.w1.wpa_supplicant1"
      string ":1.5"
      string ":1.6"

finally, here is the script I'm trying to run:

     from dbus_next.aio import MessageBus
     from dbus_next.service import (ServiceInterface,
                               method, dbus_property, signal)
     from dbus_next import Variant, DBusError,Message, MessageType, introspection, 
     import logging
     import traceback
     import asyncio
     import sys
     import os
     sys.path.append(os.path.abspath(os.path.dirname(__file__) + '/..'))
     import json

     async def main():
      bus = await MessageBus().connect()
      introspection = await bus.introspect("org.bluez", '/')
        obj = bus.get_proxy_object('org.bluez', '/',introspection)
       manager = obj.get_interface('org.freedesktop.DBus.ObjectManager') 
       test_method = await manager.GetManagedObjects()
    
    

     if __name__ == "__main__":
      loop = asyncio.get_event_loop()
      loop.set_debug(1)

         try:
            loop.run_until_complete(main())
         except KeyboardInterrupt:
             logging.info("Process interrupted")
             pass
         finally:
             loop.stop()
             loop.close() 
  
thank you a lot for your help and nice work!

**Comment by acrisci** [comment]
The introspection you've shown me is from the system bus (the `--system` flag to `dbus-send`) and your code connects to the session bus which is the default connection. Try making your `MessageBus` for the system bus like this:

```python3
from dbus_next import BusType
bus = await MessageBus(bus_type=BusType.SYSTEM).connect()
```

**Comment by redmuchroom** [comment]
haha! indeed ! thanks! and it is working ..
but now I get another issue...(actually the same issue that I had with obex...). So I would like to have the list of objects returned by the objectManager.... so I do: (based on your mpris example)

    introspection = await bus.introspect("org.bluez", '/')
    
    print(introspection.tostring())
    try:
        obj = bus.get_proxy_object('org.bluez', '/',introspection)
        manager = obj.get_interface('org.freedesktop.DBus.ObjectManager') 
        

    try2 = await manager.GetManagedObjects()

and I get the error that proxyinterface doesn't have such attribute...(GetManagedObjects)
However the introspection seems fine to me...but I guess I'm missing a stupid thing...?


> <node>

     <interface name="org.freedesktop.DBus.Introspectable">
         <method name="Introspect">
             <arg name="xml" direction="out" type="s" />
            </method>
    </interface>
    <interface name="org.freedesktop.DBus.ObjectManager">
      <method name="GetManagedObjects">
          <arg name="objects" direction="out" type="a{oa{sa{sv}}}" />
        </method>
        <signal name="InterfacesAdded">
          <arg name="object" direction="out" type="o" />
            <arg name="interfaces" direction="out" type="a{sa{sv}}" />
        </signal>
        <signal name="InterfacesRemoved">
          <arg name="object" direction="out" type="o" />
            <arg name="interfaces" direction="out" type="as" />
        </signal>
    </interface>
    <node name="org" />

 </node>
 
thanks a lot!

**Comment by acrisci** [comment]
The [proxy interface](https://python-dbus-next.readthedocs.io/en/latest/high-level-client/aio-proxy-interface.html) docs are here.

The method calls are exposed as `call_method()` to look more pythonic. You can `dir()` the interface to see the methods.

```python3
try2 = await manager.call_get_managed_objects()
```

**Comment by redmuchroom** [comment]
ok thank you! indeed it was written... I passed too fast on it... sorry for that

thanks a lot !
