### ISSUE TITLE
No non-blocking service methods 

### ISSUE THREAD

**Issue by Appadeia** [altdesktop/python-dbus-next#24]
Browsing through the examples and docs, it doesn't appear to be possible to have a `ServiceInterface` with non-blocking (`async`) method calls.

This is a bit of an issue, as my [dbus daemon](https://github.com/Appadeia/QueryKit) often does long operations, meaning that all other method calls are delayed until the larger call finishes.

**Comment by acrisci** [comment]
Yeah this should definitely be possible. Coroutines should be allowed pretty much everywhere. Related is #2.

**Comment by michallowasrzechonek-silvair** [comment]
FYI I'm interested in implementing this, expect a PR early next year

**Comment by acrisci** [comment]
Cool you got it :+1:

**Comment by acrisci** [comment]
Let me know if that works for you.
