### ISSUE TITLE
Yapf configuration mismatch

### ISSUE THREAD

**Issue by michallowasrzechonek-silvair** [altdesktop/python-dbus-next#28]
As you've probably noticed, my run of yapf removed empty lines after docstrings, while your run added them back.

Seems like there is something missing, either wrt. yapf version, or its configuration.

**Comment by acrisci** [comment]
Oh yeah what is your yapf version?

**Comment by michallowasrzechonek-silvair** [comment]
Well, I typically develop in a virtualenv, so it's "the latest stable", currently `0.29.0`

**Comment by acrisci** [comment]
Yeah my version was old. I'll fix this by setting up CI and add a build check on the formatter.
