### ISSUE TITLE
PEP561 Inline Type Hints

### ISSUE THREAD

**Issue by trickeydan** [altdesktop/python-dbus-next#30]
This project uses inline type hints, and it would be great to able to make use of them in projects utilising this library.

The procedure for this is described in [PEP 561](https://www.python.org/dev/peps/pep-0561/), but essentially boils down to adding a `py.typed` file into the module.

Once this has been added, you can also add the `Typing :: Typed` trope to the package on PyPI.

(Aside: This project looks awesome and I have a team that would be interested in contributing, let me know if that is of interest.)

**Comment by acrisci** [comment]
I would accept this into the project.

I welcome the contributions of your team :+1: . I'm usually quick to respond on this project.
