### ISSUE TITLE
Any chances for 0.1.3 release?

### ISSUE THREAD

**Issue by michallowasrzechonek-silvair** [altdesktop/python-dbus-next#41]
Hi,

Any changes to tag 0.1.3 and upload it to PyPI? We need the ObjectManager changes and due to various constraints it's not always possible to install dbus-next direct from git.

Is there anything missing you need before tagging 0.1.3?

**Comment by acrisci** [comment]
I'm good with it right now. I'll release later today.

**Comment by acrisci** [comment]
It is released.
