### ISSUE TITLE
Problem with message_handler (aio)

### ISSUE THREAD

**Issue by sbrown4** [altdesktop/python-dbus-next#44]
The coroutine that this is embedded in is run with asyncio.run_coroutine_threadsafe() from another thread. 
Any idea what I am doing wrong?

I set up the handler:
 ```
    bus = await MessageBus(bus_type=BusType.SYSTEM).connect()
    bus.add_message_handler(msg_handler)
```
The handler:
```
def msg_handler(msg):
    if msg.message_type is MessageType.ERROR:
        print(msg.error_name, msg.body)
        return True
```
Although I return True, the method call never returns.
```
        print('appkey_add call')
        await self.intf_node.call_add_app_key(self.path, dst_addr, app_idx, net_idx, False)
        print('appkey_add returned')
```
The output is as expected, just that the call never returns. The non-error case works as expected.
```
appkey_add call
org.bluez.mesh.Error.NotFound ['AppKey not found']
```
On exiting the program, I get:
```
Task was destroyed but it is pending!
task: <Task pending coro=<Menu.config_appkey_add() done, defined at ./prov_aio.py:1849> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xffffb99ae1d0>()]> cb=[_chain_future.<locals>._call_set_state() at /usr/lib/python3.7/asyncio/futures.py:355]>
```

**Comment by sbrown4** [comment]
The problem isn't related to the handler. I removed it and I still get the hang on receiving an error response. Below is the dbus-monitor of correctly processed response and the error response that hangs.
```
method call time=1586794417.794161 sender=:1.754 -> destination=org.bluez.mesh serial=20 path=/org/bluez/mesh/nodef36118cde9ac47a3882be1d5537e7124; interface=org.bluez.mesh.Node1; member=AddAppKey
   object path "/mesh/cfgclient/ele00"
   uint16 1
   uint16 1
   uint16 0
   boolean false
method call time=1586794417.799934 sender=:1.605 -> destination=:1.754 serial=842 path=/mesh/cfgclient/ele00; interface=org.bluez.mesh.Element1; member=DevKeyMessageReceived
   uint16 1
   boolean false
   uint16 0
   array of bytes [
      80 03 00 00 10 00
   ]
method return time=1586794417.800147 sender=:1.605 -> destination=:1.754 serial=843 reply_serial=20
method call time=1586794422.527159 sender=:1.754 -> destination=org.bluez.mesh serial=21 path=/org/bluez/mesh/nodef36118cde9ac47a3882be1d5537e7124; interface=org.bluez.mesh.Node1; member=AddAppKey
   object path "/mesh/cfgclient/ele00"
   uint16 1
   uint16 3
   uint16 0
   boolean false
error time=1586794422.527706 sender=:1.605 -> destination=:1.754 error_name=org.bluez.mesh.Error.NotFound reply_serial=21
   string "AppKey not found"
```

**Comment by acrisci** [comment]
What does the code you use to call the method look like?

**Comment by sbrown4** [comment]
I have a utility that talks to bluetoth-mesh. It uses cmd2 for the console commands and dbus-next for the communication. They both run in their own threads. The cmd2 stuff wants to be in the main thread. The dbus-next is in a separate thread. The dbus-next thread handles incoming messages. The cmd2 commands queue the coroutines in the dbus-next loop for specific commands with:
```
future = asyncio.run_coroutine_threadsafe(func(self, ns), main_loop)
``
where func() evaluates to the method that calls the problem code and ultimately ending up with the call to call_add_app_key that I posted above.

The case without the error return works. 
This is my first venture into dbus-next, so I probably have missed something along the way.

**Comment by acrisci** [comment]
Are you using the high level or the low level api to call the method? The high level throws exceptions and the low level does not.

**Comment by michallowasrzechonek-silvair** [comment]
@sbrown4 side note: you might have noticed that prompt-toolkit supports asyncio, so threads might not be needed

**Comment by sbrown4** [comment]
I'm using the high level call.
```
await self.intf_node.call_add_app_key(self.path, dst_addr, app_idx, net_idx, False)
```
But, no exception thrown.

**Comment by sbrown4** [comment]
Thanks for the hint. I don't need a custom handler to catch errors.
However, I sure can't find any place in the call reply notify chain that checks for MessageType.ERROR.
Is a _check_method_return() missing in aio's call()?

**Comment by acrisci** [comment]
In the low level interface, errors are treated just as another kind of method return. The higher levels get to decide how to treat errors.

Are you catching `DBusError` in that path? You might be throwing that error and it's not being reported.

As for threading, the library isn't tested with threading so that might be an issue as well.

I should really add logging to see what's going on.

**Comment by sbrown4** [comment]
It really looks like aio's call() is missing its _check_method_return().
This experimental patch seems to fix it. Can you verify that this is correct?
```
--- a/dbus_next/aio/message_bus.py
+++ b/dbus_next/aio/message_bus.py
@@ -233,6 +233,7 @@ class MessageBus(BaseMessageBus):
         future = self._loop.create_future()
 
         def reply_handler(reply, err):
+            BaseMessageBus._check_method_return(reply, err, reply.signature)
             if err:
                 future.set_exception(err)
             else:
```

**Comment by acrisci** [comment]
This causes test failures. I think I made a mistake in the docs because `call()` is not supposed to throw dbus error. The intent is really clear in the tests.

https://github.com/altdesktop/python-dbus-next/blob/018e7b77e59b334aa16324e485dd8926b171a924/test/test_aio_low_level.py#L32-L40

But if it fixes your issue, you may be onto something. If you can fix it without breaking the test, a patch is welcome.

**Comment by sbrown4** [comment]
The patch doesn't solve the problem. Ignore it.
If call_method is not supposed to raise an exception, I can use a custom message handler to field it.
However, the dbus error return message seems to hang things up such that the call_method doesn't return. I don't think this should occur on an unrecognizable return message. I'll see if I can understand what's going on.

**Comment by sbrown4** [comment]
The issue appears to be in aio ProxyInterface._add_method.method_fn. The call_method return does get checked for MessageType.ERROR in BaseProxyInterface._check_method_return. A DBusError gets raised. I didn't have the call_method in a try block and missed the exception. I don't know why the exception output got suppressed without the try. 
It appears call_method functions as currently documented. 
All in all, sorry for the noise.

**Comment by sbrown4** [comment]
Further on the above's missing coroutine exception output.
It appears that a coroutine submitted from another thread by
```
f = asyncio.run_coroutine_threadsafe()
```
 suppresses exceptions. They are only exposed if there if a 
```
result=f.result()
```
 follows. Then the exception is raised. The traceback can be retrieved with something like
```
try:
    f = future.result()
except Exception as e:
    print("".join(traceback.TracebackException.from_exception(e).format()))
```
