### ISSUE TITLE
Getting updates of ListNames

### ISSUE THREAD

**Issue by bibi21000** [altdesktop/python-dbus-next#48]
Hi
First of all ... ty for this pure python lib which is perfect for virtual env

More a support question than an issue.

I use : 
        message = Message(destination="org.freedesktop.DBus",
                          member="ListNames",
                          interface="org.freedesktop.DBus",
                          path="/org/freedesktop/DBus",
                          signature="",
                          body=[])

to retrieve all services connected to DBus.

But I don't know how to get 'updates' of this list, ie new servers or servers that leaved ... like d-feet do.
How can i do it ?

**Comment by acrisci** [comment]
https://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-name-owner-changed

**Comment by bibi21000** [comment]
Perfect
Thank you
