### ISSUE TITLE
New object signal

### ISSUE THREAD

**Issue by hxss** [altdesktop/python-dbus-next#51]
Hello. Can I subscribe to registration of new objects in bus?
For example I want to know when new device will be added in `org.bluez`.
Or maybe its possible to listen signals from all instances of specific interface(`PropertiesChanged` from any bluez device)?

**Comment by acrisci** [comment]
https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-objectmanager

**Comment by hxss** [comment]
thx
