### ISSUE TITLE
Type mixup between x (int64) and i (int32)

### ISSUE THREAD

**Issue by Natureshadow** [altdesktop/python-dbus-next#58]
Trying to use the `get_position` method on an MPRIS interface, in the example from the README, I get `dbus_next.errors.DBusError: property returned unexpected signature "x"`. This is because the property is typed `x`, a signed int64, but introspection thinks it is typed `i`.

**Comment by acrisci** [comment]
The introspection is wrong.

https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Property:Position

Position property is supposed to be type x. You have control of what introspection you give to the high level client so you should change it there.
