### ISSUE TITLE
 dbus_next.errors.DBusError: ipv4.addresses: this property cannot be empty for 'method=manual'

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [altdesktop/python-dbus-next#66]
Hey, I'm trying to configure an IPv4 connection of network manager. Have you by coincidence ever tried that? I have no clue what I'm doing wrong.

I actually posted that issue already on SO but I just thought that maybe you guys might have done something similar already and would like to draw your attention to that issue :) https://stackoverflow.com/questions/64326479/dbus-next-errors-dbuserror-ipv4-addresses-this-property-cannot-be-empty-for-m

Other features like adding/removing/activating connections work completely flawless. But this is giving me a considerable pain in the ass.

**Comment by acrisci** [comment]
I looked up the error in case there could be a library issue, but it seems like that field can be sent over dbus and you'll get the error anyway if no addresses end up being configured.

https://mail.gnome.org/archives/networkmanager-list/2016-December/msg00061.html

The `addresses` member is deprecated. Try removing it and see what happens.

**Comment by HerrMuellerluedenscheid** [comment]
Hey,
thanks for the hint. Without the `addresses` member the exception stays the same. I also tested network managers `call_reapply` method on the device interface. I ensured that the device is activated and connection established. The exception stays the same.
Well, this rather seems an issue of dbus on the network manager side.

**Comment by HerrMuellerluedenscheid** [comment]
It was actually a problem related to the address data that was sent to the network manager which was throwing this enigmatic error. Thanks for your input though!
