### ISSUE TITLE
Can't connect to system bus after migrating from 0.1.4 to 0.2.1

### ISSUE THREAD

**Issue by bibi21000** [altdesktop/python-dbus-next#70]
Hi,
After migration i've got the following error in logs : 
exception=DBusError('Connection ":1.1219" is not allowed to own 
the service "xx.yy.zz..." due to security policies in the configuration file')
Ofc my configuration is ok ... and worked fine with all previous releases.
Any idea ?
TIA

**Comment by acrisci** [comment]
I can't think of anything in this release that would affect that. The message was sent and received successfully, so it's possible the error message is valid. The majority of the testing is for the session bus, but I have a test suite in a project I'm using that takes a name on the system bus and I'm not having a problem with it.

If you have a simple setup I can use to reproduce the error, I'll check it out and add it to the test suite.

**Comment by bibi21000** [comment]
i aplogize ... problem was between screen and keyboard ... me )))
I had propagated a bad configuration file for DBus on our CI server.
Ty a lot for this lib
