### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sphh** [altdesktop/python-dbus-next#88]
Thank you for your commit https://github.com/altdesktop/python-dbus-next/commit/04e7c0428ec2e4020d4b95aa70e10feb8e53e22e, which closed my question #86.

May I ask you a favour? Could you please push a new release to PyPi? I want to release my [`mopidris`](https://codeberg.org/sph/mopidris) program and push it to PyPi, but it depends on these new asynchronous properties.

Thanks.

**Comment by acrisci** [comment]
Yes, I will release pretty soon, probably in a few days.

**Comment by sphh** [comment]
Oh, thanks!

Can you already disclose the secret, which version number it will get? 0.2.3 or 0.3.0 or an even higher one?

**Comment by acrisci** [comment]
Very likely 0.2.3, but I won't tell you for sure because I mess up a release sometimes.

**Comment by sphh** [comment]
Well, these things can happen, can't they?

Thanks. Then I will prepare mine for 'dbus_next>=0.2.3' (and change it later if really needed).

**Comment by sphh** [comment]
Hi @acrisci: May I ask gently, how the release plan for 0.2.3 looks like?

**Comment by sphh** [comment]
@acrisci: Is there anything I could help to release the next version?

**Comment by acrisci** [comment]
It is released

**Comment by sphh** [comment]
So many thanks!
