### ISSUE TITLE
Better support for ofono 

### ISSUE THREAD

**Issue by pkcinna01** [altdesktop/python-dbus-next#89]
Ofono is a popular framework for interacting with cell phones via bluetooth.  I could not figure out how to get events for a specific phone or phone call without having access to a proxy object. 

```
#only listen for phone calls on specific phone defined by self.modem_path
self.call_added_sig_receiver = sysBus.add_signal_receiver(self.call_added_cb,
	signal_name="CallAdded",
	bus_name="org.ofono",
	dbus_interface="org.ofono.VoiceCallManager",
	path=self.modem_path)

#only listen to a specific all on a specific phone
self.prop_changed_sig_receiver = sysBus.add_signal_receiver(self.voice_call_prop_change_cb,
	signal_name="PropertyChanged",
	bus_name="org.ofono",
	dbus_interface="org.ofono.VoiceCall",
	path=self.call_path)
```

**Comment by acrisci** [comment]
Please read the docs for the low level interface https://python-dbus-next.readthedocs.io/en/latest/low-level-interface/index.html

There's plenty of examples there to show you how to use it.

**Comment by pkcinna01** [comment]
Sorry.  I couldn't figure it out with the low level api.  None of the examples seemed to address selectively filtering signals by just a path.   I tried to make it work with listeners but that involved using if/else code to filter for paths which would not scale well. 
    On Thursday, April 29, 2021, 12:45:44 PM EDT, Tony Crisci ***@***.***> wrote:  
 
 


Please read the docs for the low level interface https://python-dbus-next.readthedocs.io/en/latest/low-level-interface/index.html

There's plenty of examples there to show you how to use it.

**Comment by acrisci** [comment]
One useful tip for working with introspected classes like this is to use statements like `print(dir(interface))`. Other than that i don't know how to help without having a specific question to answer.

**Comment by pkcinna01** [comment]
I guess the question is how to convert the code below to the interface for one object defined by modem_path.  There will be lots of VoiceCallMangers created dynamically.

`modem_interface = dbus.Interface(sysBus.get_object('org.ofono', modem_path),'org.ofono.VoiceCallManager')`

With dbus-next, i can get the proxy_object but not clear how to get the interface from there...  my hope was calling proxy_object.get_interface() with no arguments would return the interface to keep it simple.
