### ISSUE TITLE
missing timeout for dbus calls via proxy object

### ISSUE THREAD

**Issue by pruckebusch** [altdesktop/python-dbus-next#92]
When a dbus call via a proxy object method does not return, it is awaited indefinitely by the caller.
It might be a good idea to also add timeouts to the method and properties added on a proxy-object, as is done for the introspect method (https://github.com/altdesktop/python-dbus-next/pull/7).

We saw this issue when using dbus-next to in combination with bluez.

**Comment by michallowasrzechonek-silvair** [comment]
How about `asyncio.wait_for`?

**Comment by acrisci** [comment]
I think it was a mistake to add that timeout param. I should deprecate it. I don't want to add a timeout to everything. It's better to use the built in asyncio timeout function.

**Comment by pruckebusch** [comment]
Thanks for the quick response.

IMHO it is something that should be facilitated by the library, i.e. embed asyncio timeout inside the calls.
Otherwise all calls need to be protected by the user which makes the business logic of an application less readable.

Anyway, as we saw this behavior we will add the functionality. If desired, we can always make a PR.
